### ISSUE TITLE
Simplify Journal and InMemoryJournalActor types parameters

### ISSUE THREAD

**Issue by tjaskula** [vlingo-net/vlingo-net-symbio#6]
It would be nice to simplify because of this kind hard to grasp signatures:

`_journal = Journal<string>.Using<InMemoryJournalActor<string, TextEntry, TextState>, TextEntry, TextState>(_world.Stage, _dispatcher);`

For `InMemoryJournalActor `it would be nice to limit it just to `InMemoryJournalActor<TEntry, TState>`.

For `Journal<string>` under the hood converts to `IEntry<string>` so it has to match the actor entry `TextEntry` (implementing `IEntry<string>`).

@VaughnVernon Do we have to keep both, Entry and State? I'm looking for some ideas to discuss here to simplify the usage.

**Comment by VaughnVernon** [comment]
@tjaskula Seems better to simplify. I don't know why there are duplicates. Do you? Seems different from java.

**Comment by tjaskula** [comment]
Yes, because java used a lot of `<?>` almost everywhere and I certainly missed the intent of what was going under the hood. Many types and constraint, so I think that I missed some understanding.
Using this API is overwhelming even for someone who has implemented it :)

**Comment by VaughnVernon** [comment]
Of course make it simple. Sorry the java is a bit confusing. Some said: "You have a type problem to solve so you decide to use Java generics. Now you have two problems."

**Comment by tjaskula** [comment]
Ok, I leave it for after.

**Comment by tjaskula** [comment]
Ok @VaughnVernon. I've refactored everything and simplified it a lot :) I'll push shortly
